pod_qc_user: podPeople
pod_qc_pass: 1956InvasionOfThe
filmdb_service_username: filmdbService
filmdb_service_pass: RalphWiggum1989
memnon_xml: "https://pod.mdpi.iu.edu/responses/objects/memnon_qc/<MDPI_BARCODE>"
digitized: "https://pod.mdpi.iu.edu/responses/objects/<MDPI_BARCODE>/digital_workflow"